{% set name = "yaqd-horiba" %}
{% set version = "2020.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 421883b97dac07dd4f2bfd198b1af75835e22b2430e6199983e6cca233cfc838

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-micro-hr = yaqd_horiba._microhr:MicroHR.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - pyusb
    - yaqd-core >=2020.06.3
  run:
    - python >=3.7
    - pyusb
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_horiba
  commands:
    - pip check
    - yaqd-micro-hr --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for Horiba Jobin Yvon hardware
  dev_url: https://gitlab.com/yaq/yaqd-horiba
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
